### ISSUE TITLE
settings-app doesn't compile

### ISSUE THREAD

**Issue by n3rdopolis** [papyros/settings-app#3]
It seems a file is missing from the repository?

This is the output from qmake and make:
RCC: Error in 'papyros-settings.qrc': Cannot find file 'qml/SettingsModel.qml'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /opt/include/QtQuick -isystem /opt/include/QtWidgets -isystem /opt/include/QtGui -isystem /opt/include/QtQml -isystem /opt/include/QtNetwork -isystem /opt/include/QtCore -I. -I/opt/mkspecs/linux-g++ -o main.o src/main.cpp
/opt/bin/rcc -name papyros-settings papyros-settings.qrc -o qrc_papyros-settings.cpp
RCC: Error in 'papyros-settings.qrc': Cannot find file 'qml/SettingsModel.qml'
Makefile:689: recipe for target 'qrc_papyros-settings.cpp' failed
make: **\* [qrc_papyros-settings.cpp] Error 1
make: **\* Waiting for unfinished jobs....
PackageCompileSource finished in 2 seconds

Thanks.

**Comment by fedya** [comment]
solved?

**Comment by n3rdopolis** [comment]
Doesn't seem so... There doesn't seem to be any new commits

**Comment by iBelieve** [comment]
This is fixed now. The project is now built using `cmake` and has details in the README.
